--- # my handlers section

- hosts: webservers
  become: yes
  user: ansible
  connection: ssh
  tasks:

    - name: installing httpd software
      action: yum name=httpd state=present
      notify: service httpd start

  handlers:
    - name: service httpd start
      action: service name=httpd state=started
